vpn:
  build: .
  net: bridge #you can change to "host" if needed
  environment:
    - SERVER=vpn.server.com
    - USER=username
    - PASSWORD=password
    - DUMMYIP=iptosendpackets
  devices:
    - /dev/ppp
  cap_add:
    - NET_ADMIN
  restart: unless-stopped
